In [1]:
import numpy as np

# 배열의 형태(shape) 변경

## reshape()을 이용한 차원 변경
- `numpy.reshape(a, newshape)` 또는 `ndarray.reshape(newshape)`
    - 둘 다 원본은 변경되지 않는다.
    - a: 형태를 변경할 배열
    - newshape : 변경할 형태 설정. 
        - 원소의 개수를 유지하는 shape으로만 변환 가능하다.(동일한 개수만 가능)
        - (x, -1) 처럼 넣을 경우 -1은 구조에 맞게 알아서 출력해달라는 뜻이다.

In [11]:
x = np.arange(20)
print(x.shape)

r1 = np.reshape(x, (4, 5))
print(r1.shape)

r2 = np.reshape(x, (2, 2, 5))
print(r2.shape)

(20,)
(4, 5)
(2, 2, 5)


In [12]:
r3 = x.reshape((2, 2, 5))
# 또는
r3 = x.reshape(2, 2, 5)

r3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [13]:
# 원본 배열의 size와 reshape size는 동일하도록 설정
print(x.size)
x.reshape(2, 3, 3)

20


ValueError: cannot reshape array of size 20 into shape (2,3,3)

In [21]:
# 축의 값이 -1이 되면 나머지 축에 맞는 사이즈를 알아서 맞추도록 한다.
print(x.reshape(5, -1))
print(x.reshape(1, -1))

# 사이즈에 맞지 않는 경우엔 에러
x.reshape(6, -1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


ValueError: cannot reshape array of size 20 into shape (6,newaxis)

## 차원 늘리기(확장)
- dummy axis를 추가
    - dummy axis: size가 1인 axis(축)
    
### numpy.newaxis 속성을 이용해 차원 늘리기
- size가 1인 rank를 늘릴때 사용한다. 
    - 지정한 axis에 size 1인 축을 추가한다.
- slicing에 사용하거나 indexing에 `...`과 같이 사용한다.
    - slicing의 경우 원하는 위치의 축을 늘릴 수 있다.
    - index에 ...과 사용하는 경우 첫번째나 마지막 축을 늘릴때 사용한다.
    - 주로 ...을 자주 사용한다.
        - 첫번째나 마지막 인덱스에만 사용된다
        - x[np.newaxis, ..., np.axis]는 불가능!
        - 보통 중간을 늘리는 경우는 없다.

In [24]:
x.shape

(20,)

In [25]:
# (20,) => (20,1)
r = x[:, np.newaxis]
print(r.shape)
r

(20, 1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [26]:
# (20,) => (1, 20)
r = x[np.newaxis, :]
print(r.shape)
r

(1, 20)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [27]:
# ...는 전체를 의미한다. 축을 늘릴 때만 사용되는 변수?이다.
r2 = x[..., np.newaxis]
r2.shape

(20, 1)

In [28]:
# (20,) => (1, 20)
r2 = x[np.newaxis, ...]
r2.shape

(1, 20)

In [29]:
r3 = x[np.newaxis, np.newaxis, ...]
r3.shape

(1, 1, 20)

### indexing에 ... 과 같이 사용
- ndarray[..., np.newaxis]
- 첫번째 축이나 마지막 축을 늘릴때만 사용가능

In [32]:
x = np.arange(12).reshape(3, 4)
print(x.shape)
x

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# (3, 4) => (3, 1, 4)
r = x[:, np.newaxis, :]
print(r.shape)
r

(3, 1, 4)


array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

### numpy.expand_dims (배열, axis)
- 매개변수로 받은 배열에 지정한 axis의 rank를 확장한다.

In [36]:
print(x.shape)

# (3, 4) => (1, 3, 4)
# x[np.newaxis, ...]
r = np.expand_dims(x, axis=0)
r.shape

(3, 4)


(1, 3, 4)

In [38]:
# (3, 4) => (3, 1, 4, 1)
r = np.expand_dims(x, axis=[1,3])
r.shape

(3, 1, 4, 1)

## 차원 줄이기(축소)

### numpy.squeeze(배열, axis=None), 배열객체.squeeze(axis=None)
- 배열에서 지정한 축(axis)을 제거하여 차원(rank)를 줄인다.
- 제거하려는 축의 size는 1이어야 한다.
- 축을 지정하지 않으면 size가 1인 모든 축을 제거한다.
    - (3,1,1,2) => (3,2)

In [39]:
x = np.arange(12).reshape(3, 1, 4, 1, 1)
x.shape

(3, 1, 4, 1, 1)

In [40]:
# axis 생략 -> None -> 모든 dummy axis를 제거
r = x.squeeze()
r.shape

(3, 4)

In [43]:
r = x.squeeze(axis=1)
r.shape

(3, 4, 1, 1)

In [45]:
# size가 1이 아닌 axis만 제거 가능하다
x.squeeze(axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [48]:
# 다수의 축을 제거하는 경우 튜플로 묶어서 설정한다.
x.squeeze(axis=(1, 3))

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### 배열객체.flatten()
- 다차원 배열을 1차원으로 만든다.

In [49]:
r = x.flatten()
r.shape

(12,)

## numpy.append(), numpy.insert(), numpy.delete()
- ### append(배열, 추가할값, axis=None)
    - 배열의 마지막 index에 추가할값을 추가
    - 원본은 변경하지 않고 새로운 배열을 만든다.
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 추가한다.
- ### insert(배열, index, 추가할값, axis=None)
    - 배열의 index에 추가할값을 추가. 
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삽입한다.
- ### delete(배열, 삭제할index, axis=None)  
    - 배열의 삭제할index의 값들을 삭제한다.
    - 삭제할 index는 index 또는 slice
    - axis : 축 지정
        - None(기본값) : flatten 한 뒤 삭제한다.

### append()

In [50]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [52]:
r = np.append(a, 100)
print(r)
a

[  1   2   3 100]


array([1, 2, 3])

In [53]:
# 여러 값을 한번에 추가
r = np.append(a, [10, 20, 30])
r

array([ 1,  2,  3, 10, 20, 30])

In [54]:
b = np.arange(12).reshape(3, 4)
print(b.shape)
b

(3, 4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
# axis 지정을 안하면 1차원으로 변경 후 추가
np.append(b, 100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 100])

In [58]:
np.append(b, [[10],[20],[30]], axis=1)

array([[ 0,  1,  2,  3, 10],
       [ 4,  5,  6,  7, 20],
       [ 8,  9, 10, 11, 30]])

In [72]:
np.append(b, [[100, 200, 300, 400]], axis=0)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [100, 200, 300, 400]])

### insert

In [73]:
a = np.array([1, 2, 3])

# index 1에 100을 삽입
r = np.insert(a, 1, 100)
r

array([  1, 100,   2,   3])

In [75]:
# 한번에 여러 값을 insert
r = np.insert(r, 1, [10, 20, 30, 40])
r

array([  1,  10,  20,  30,  40, 100,   2,   3])

In [76]:
l = [
    [1, 1],
    [2, 2],
    [3, 3]
]
b = np.array(l)
print(b.shape)
b

(3, 2)


array([[1, 1],
       [2, 2],
       [3, 3]])

In [77]:
# 다차원(2차원) 배열에서 axis를 지정하지 않으면 1차원으로 변경후 insert
np.insert(b, 1, 1000)

array([   1, 1000,    1,    2,    2,    3,    3])

In [80]:
np.insert(b, 2, [[10, 10]], axis=0)

array([[ 1,  1],
       [ 2,  2],
       [10, 10],
       [ 3,  3]])

In [81]:
np.insert(b, 2, [[10, 10],[20, 20]], axis=0)

array([[ 1,  1],
       [ 2,  2],
       [10, 10],
       [20, 20],
       [ 3,  3]])

In [82]:
# 동일한 값을 넣을 경우 정수
np.insert(b, 1, 5, axis=1)

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

In [88]:
# 서로 다른 값을 넣을 경우 열백터로 넣는다.
np.insert(b, 1, [5, 50, 500], axis=1)

array([[  1,   5,   1],
       [  2,  50,   2],
       [  3, 500,   3]])

In [89]:
# 한 열에 여러 값을 넣는 경우 다음과 같이 작성한다.
np.insert(b, 1, [[100], [200]], axis=1)

array([[  1, 100, 200,   1],
       [  2, 100, 200,   2],
       [  3, 100, 200,   3]])

### delete

In [95]:
a = np.arange(20)

In [97]:
# 여러 index 삭제시 []로 묶어준다.
r = np.delete(a, [1, 7, 8])
r

array([ 0,  2,  3,  4,  5,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [98]:
# np.s_[slicing문법]
# 배열과 상관없이 slicing 범위만 지정할 때 사용하는 numpy 변수
r = np.delete(a, np.s_[2:11])
r

array([ 0,  1, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [99]:
# 다차원 배열에서 axis를 지정안하면 flatten후 삭제
np.delete(b, 1)

array([1, 2, 2, 3, 3])

In [100]:
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [101]:
np.delete(b, 1, axis=0)

array([[1, 1],
       [3, 3]])

In [ ]:
np.delete()

## 배열 합치기
- ### np.concatenate(합칠 배열리스트, axis=0)
    - 여러 배열을 **축의개수(rank)**를 유지하며 합친다.
    - axis 파라미터 : 축지정
        - 지정된 축을 기준으로 합친다. 
        - default : 0
    - 합치는 배열의 축의 개수(rank) 은 같아야 한다.
    - axis속성으로 지정한 축 이외의 축의 크기가 같아야 한다.
    - 결과의 축의개수(rank)는 대상 배열의 rank와 같다.
        - 1차원끼리 합치면 1차원결과가 나옴
- ### 합칠 대상 배열의 rank가 2일 경우(행렬) 
    - vstack()
    - hstack()
    - np.concatenate()의 간단버전
        - concatenate에서 axis만 사라졌다고 생각하면 된다>
- ### vstack(합칠배열리스트)
    - 수직으로 쌓는다.
    - concatenate() 의 axis=0 와 동일
    - 합칠 배열들의 열수가 같아야 한다.
- ### hstack(합칠배열리스트)
    - 수평으로 쌓는다.
    - concatenate() 의 axis=1 와 동일
    - 합칠 배열들의 행 수가 같아야 한다.

### concatenate()

- axis=0 이면 0이 늘어난다. 0을 기준으로 합치므로 (그래서 밑으로 (행이 늘어남)붙는다.)
    - 그래서 각 배열의 컬럼 수가 같아야 한다. 
- axis=1 이면 1이 늘어난다. 1을 기준으로 합치므로 (그래서 옆으로 (컬럼이 늘어남) 붙는다.)
    - 그래서 각 배열의 행수가 같아야 한다.

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(2, 6)
b = np.arange(10, 22).reshape(2, 6)
c = np.arange(20, 32).reshape(2, 6)
a.shape, b.shape, c.shape

((2, 6), (2, 6), (2, 6))

In [3]:
r = np.concatenate([a, b, c], axis=0)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31]])

In [4]:
r2 = np.concatenate([a, b, c], axis=1)
r2

array([[ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23,
        24, 25],
       [ 6,  7,  8,  9, 10, 11, 16, 17, 18, 19, 20, 21, 26, 27, 28, 29,
        30, 31]])

In [8]:
x = np.arange(12).reshape(2, 2, 3)
y = np.arange(10, 26).reshape(2, 2, 4)

# axis가 2가 아니면 에러가 난다.
r3 = np.concatenate([x, y], axis=2)
r3

array([[[ 0,  1,  2, 10, 11, 12, 13],
        [ 3,  4,  5, 14, 15, 16, 17]],

       [[ 6,  7,  8, 18, 19, 20, 21],
        [ 9, 10, 11, 22, 23, 24, 25]]])

### vstack()
- 아래에 붙이는 개념이므로 열수가 맞아야 한다. 
- axis=0과 동일

In [ ]:
x = np.arange(12).reshape(2, 2, 3)
y = np.arange()

v1 = 

### hstack()
- 옆으로 붙이는 것이므로 행 수가 같아야 한다.
- axis=1과 동일

## 배열 분할 하기
- ### split(배열, 분할기준, axis)
    - 지정한 축을 기준으로 배열을 나눈다.. 
    - 반환값: 분할한 narray를 가진 리스트로 리턴.
    - 배열: 분할할 배열
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
    - axis(축)
        - 분할할 기준 축을 지정한다. axis = 0 (기본) 
        - 2D의 경우 axis=0: 행 기준 분할, axis=1: 열 기준 분할
- ### vsplit(배열, 분할기준)
    - 행 기준 분할
    - split()의 axis=0과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- ### hsplit(배열, 분할기준)
    - 열 기준 분할
    - split()의 axis=1과 동일
    - 분할기준
        - 정수 : 지정 개수만큼 분할
        - 리스트 : 분할 기준 index들
- **주의:** 분할기준을 정수(개수)로 할 경우 분할후 원소수가 같아야 한다. 

In [17]:
b = np.arange(48).reshape(8, 6)
print(b.shape)
b

(8, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [18]:
r = np.split(b, 2, axis=1)
print(len(r))
r[0].shape, r[1].shape

2


((8, 3), (8, 3))

In [20]:
r = np.split(b, 3, axis=1)
r[0].shape, r[1].shape, r[2].shape

((8, 2), (8, 2), (8, 2))

In [21]:
c = np.arange(4*4*8).reshape(4, 4, 8)
c.shape

(4, 4, 8)

In [22]:
r = np.split(c, 2, axis=0)
len(r)

2

In [23]:
r[0].shape, r[1].shape

((2, 4, 8), (2, 4, 8))

In [24]:
r = np.split(c, [3, 6], axis=2)
r

[array([[[  0,   1,   2],
         [  8,   9,  10],
         [ 16,  17,  18],
         [ 24,  25,  26]],
 
        [[ 32,  33,  34],
         [ 40,  41,  42],
         [ 48,  49,  50],
         [ 56,  57,  58]],
 
        [[ 64,  65,  66],
         [ 72,  73,  74],
         [ 80,  81,  82],
         [ 88,  89,  90]],
 
        [[ 96,  97,  98],
         [104, 105, 106],
         [112, 113, 114],
         [120, 121, 122]]]),
 array([[[  3,   4,   5],
         [ 11,  12,  13],
         [ 19,  20,  21],
         [ 27,  28,  29]],
 
        [[ 35,  36,  37],
         [ 43,  44,  45],
         [ 51,  52,  53],
         [ 59,  60,  61]],
 
        [[ 67,  68,  69],
         [ 75,  76,  77],
         [ 83,  84,  85],
         [ 91,  92,  93]],
 
        [[ 99, 100, 101],
         [107, 108, 109],
         [115, 116, 117],
         [123, 124, 125]]]),
 array([[[  6,   7],
         [ 14,  15],
         [ 22,  23],
         [ 30,  31]],
 
        [[ 38,  39],
         [ 46,  47],
         [ 54, 

## hsplit()/vsplit()
- vsplit() : axis=0
- hsplit() : axis=1
- 행렬(2차원 배열)용 함수. (다차원 배열에도 사용가능)

In [25]:
b.shape

(8, 6)

In [26]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47]])

In [29]:
# split(b, 2, axis=0)
r = np.vsplit(b, 2)
len(r)

2

In [30]:
x, y = r
x.shape, y.shape

((4, 6), (4, 6))

In [33]:
# 2, 5, 7을 기준으로 4조각 내라
r = np.vsplit(b, [2, 5, 7])
r

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41]]),
 array([[42, 43, 44, 45, 46, 47]])]

In [35]:
# axis=1이고 3등분 하라
r = np.hsplit(b, 3)
r

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31],
        [36, 37],
        [42, 43]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33],
        [38, 39],
        [44, 45]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35],
        [40, 41],
        [46, 47]])]