# 배열을 파일에 저장 및 불러오기
- 바이너리로 저장 -> text로 못봄
- 텍스트로 저장 -> text로 볼 수 있음
- ## 바이너리 파일로 저장/불러오기
    - ### np.save("파일경로", 배열)
        - 하나의 파일에 무조건 `배열 하나만 저장` 가능
        - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
        - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
    - ### np.load("파일경로") 
        - 파일에 저장된 배열을 불러온다.
    - ### np.savez("파일경로", 이름=배열, 이름=배열, ...)
        - 하나의 파일에 `여러개의 배열을 저장`할 때 사용
        - 파일명에 확장자로 npz가 붙는다.
        - 내부적으로 압축해서 저장한다.
        - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 
- ## 텍스트 파일로 저장하고 불러오기
    - ### savetxt("파일경로", 배열 [, delimiter='공백') 
        - 텍스트 형태로 저장.
        - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
        - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
    - ### loadtxt("파일경로" [,dtype=float, delimiter=공백)

In [1]:
import numpy as np

In [5]:
a = np.array([1, 10, 5, 20])
b = np.ones((3, 3, 5))
# 평균:10, 표준편차:2
c = np.random.normal(10, 2, size=(5, 10))

a.shape, b.shape, c.shape

((4,), (3, 3, 5), (5, 10))

In [13]:
a, b, c

(array([ 1, 10,  5, 20]),
 array([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]),
 array([[11.24434325,  7.97383961,  8.25901366, 12.45569231, 13.56820154,
          9.02540971, 10.99933369, 11.09507828,  8.77573047, 11.45561982],
        [13.41727621, 11.1259044 ,  7.48908994,  7.79494977,  9.76887359,
          7.34724858,  8.59552338,  9.78145799, 10.15581934,  5.46403099],
        [ 9.57784474, 13.40481044, 12.15182209, 10.3111626 , 10.82668426,
         12.39639977,  9.27983239, 13.29165011, 12.21588419,  6.92188487],
        [10.93794014, 11.19596425, 10.81133312, 12.67292336, 10.90641519,
          9.39027547, 11.39618851, 12.53987289,  8.36823515,  8.18240559],
        [10.12238121, 11.80813568,  9.20602114,  9.31061088,  9.90235089,
         10.0715

In [6]:
# binary 파일에 배열을 저장
# 한 파일에 배열 하나 - save(경로+파일명, 배열)
# 경로 : 상대경로(현재 directory 기준 경로) 
#     or 절대경로(root dir부터 전체 경로) - c:\a\b\abc

# 파일의 확장자를 생략해도 npy로 자동 생성된다.
np.save("data/array_a", a)
np.save("data/array_b.npy", b)
# .npy(확장자)로 끝나지 않으면 다 파일명이 된다.
# 확장자처럼 생겼지만 array.c.npy로 파일이 생성된다.
np.save("data/array.c", c)

In [9]:
# 불러오기(load) - load()
# 불러올 때는 확장자를 붙여야 한다.
a2 = np.load('data/array_a.npy')
b2 = np.load('data/array_b.npy')
c2 = np.load('data/array.c.npy')

a2.shape, b2.shape, c2.shape

((4,), (3, 3, 5), (5, 10))

In [12]:
a2, b2, c2

(array([ 1, 10,  5, 20]),
 array([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],
 
        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]),
 array([[11.24434325,  7.97383961,  8.25901366, 12.45569231, 13.56820154,
          9.02540971, 10.99933369, 11.09507828,  8.77573047, 11.45561982],
        [13.41727621, 11.1259044 ,  7.48908994,  7.79494977,  9.76887359,
          7.34724858,  8.59552338,  9.78145799, 10.15581934,  5.46403099],
        [ 9.57784474, 13.40481044, 12.15182209, 10.3111626 , 10.82668426,
         12.39639977,  9.27983239, 13.29165011, 12.21588419,  6.92188487],
        [10.93794014, 11.19596425, 10.81133312, 12.67292336, 10.90641519,
          9.39027547, 11.39618851, 12.53987289,  8.36823515,  8.18240559],
        [10.12238121, 11.80813568,  9.20602114,  9.31061088,  9.90235089,
         10.0715

In [15]:
c.dtype, c2.dtype

(dtype('float64'), dtype('float64'))

In [17]:
# 한 파일에 여러 배열 저장 - savez(경로, 이름=배열, 이름=배열, ...)
# 확장자가 npz로 생성된다.
# npy : 하나의 배열이 저장된 파일, npz : 여러 배열이 저장된 파일
np.savez('data/array', a=a, b=b, c=c)

In [21]:
arrays = np.load('data/array.npz')
arrays, arrays.files

(<numpy.lib.npyio.NpzFile at 0x1e74747d0a0>, ['a', 'b', 'c'])

In [23]:
# 각 배열을 조회 - index 연산자 사용
a3 = arrays['a']
b3 = arrays['b']
c3 = arrays['c']

a3.shape, b3.shape, c3.shape

((4,), (3, 3, 5), (5, 10))

In [24]:
# text파일로 저장 => csv로 저장
# 1차원, 2차원 배열만 저장 가능
# savetxt(), loadtxt()
np.savetxt('data/a.csv', a)

In [26]:
a4 = np.loadtxt('data/a.csv', dtype=np.int)
a4

array([ 1, 10,  5, 20])

In [30]:
print(b.shape)
# 3차원이라서 에러가 난다.
np.savetxt('data/b.csv', b)

(3, 3, 5)


ValueError: Expected 1D or 2D array, got 3D array instead

In [32]:
# 저장시 delimiter가 없다면
np.savetxt('data/c.csv', c)
c4 = np.loadtxt('data/c.csv')
c4

array([[11.24434325,  7.97383961,  8.25901366, 12.45569231, 13.56820154,
         9.02540971, 10.99933369, 11.09507828,  8.77573047, 11.45561982],
       [13.41727621, 11.1259044 ,  7.48908994,  7.79494977,  9.76887359,
         7.34724858,  8.59552338,  9.78145799, 10.15581934,  5.46403099],
       [ 9.57784474, 13.40481044, 12.15182209, 10.3111626 , 10.82668426,
        12.39639977,  9.27983239, 13.29165011, 12.21588419,  6.92188487],
       [10.93794014, 11.19596425, 10.81133312, 12.67292336, 10.90641519,
         9.39027547, 11.39618851, 12.53987289,  8.36823515,  8.18240559],
       [10.12238121, 11.80813568,  9.20602114,  9.31061088,  9.90235089,
        10.07158732,  7.27967814,  8.45781085,  9.4492632 , 10.81606861]])

In [34]:
# 저장시 delimiter가 있다면 load시에도 delimiter를 설정해야 에러가 안난다.
np.savetxt('data/c.csv', c, delimiter=',')
c4 = np.loadtxt('data/c.csv', delimiter=',')
c4

array([[11.24434325,  7.97383961,  8.25901366, 12.45569231, 13.56820154,
         9.02540971, 10.99933369, 11.09507828,  8.77573047, 11.45561982],
       [13.41727621, 11.1259044 ,  7.48908994,  7.79494977,  9.76887359,
         7.34724858,  8.59552338,  9.78145799, 10.15581934,  5.46403099],
       [ 9.57784474, 13.40481044, 12.15182209, 10.3111626 , 10.82668426,
        12.39639977,  9.27983239, 13.29165011, 12.21588419,  6.92188487],
       [10.93794014, 11.19596425, 10.81133312, 12.67292336, 10.90641519,
         9.39027547, 11.39618851, 12.53987289,  8.36823515,  8.18240559],
       [10.12238121, 11.80813568,  9.20602114,  9.31061088,  9.90235089,
        10.07158732,  7.27967814,  8.45781085,  9.4492632 , 10.81606861]])